name: dotnet test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        env:
          DOTNET_TEST_NEW_EXPERIENCE: "true"
        run: |
          dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-results
          path: '**/test-results.trx'