name: dotnet test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      checks: write
      pull-requests: write
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        env:
          TESTINGPLATFORM_RESULT_REPORT_TRX: "true"
        run: |
          ./test/Tests.Fx.Net/bin/Release/net10.0/Tests.Fx.Net

      - name: Publish Test Report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: xUnit 3 Tests Report
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx

      - name: Upload Test Results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-results
          path: '**/TestResults/*.trx'